### ISSUE TITLE
[feat] support for Linkerd service mesh

### ISSUE THREAD

**Issue by schwichti** [dspace-group/simphera-reference-architecture-aws#43]
Add to nginx helm chart configuration:
```yaml
controller:
    podAnnotations:
      linkerd.io/inject: enabled
```

**Comment by schwichti** [comment]
SIMPHERA helm values need to have this:
```yaml
global:
  simphera:
    ingress:
      additionalAnnotations:
        nginx.ingress.kubernetes.io/service-upstream: "true"   
```
